black-List-biome:
  - OCEAN
black-List:
  - AIR
  - LAVA
  - WATER
  - SNOW
  - BEDROCK
  - CACTUS
  - FIRE
  - END_PORTAL
  - END_CRYSTAL
  - END_PORTAL_FRAME
  - NETHER_PORTAL
  - ACACIA_LEAVES
  - AZALEA_LEAVES
  - BIRCH_LEAVES
  - OAK_LEAVES
  - DARK_OAK_LEAVES
  - SPRUCE_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - JUNGLE_LEAVES
  - VOID
  - VOID_AIR
  - WEEPING_VINES
  - TWISTING_VINES
  - CRIMSON_ROOTS
  - NETHER_SPROUTS
  - WARPED_FUNGUS
  - CRIMSON_FUNGUS
  - GRASS
  - BAMBOO
  - CHORUS_PLANT
  - CHORUS_FLOWER
  - KELP_PLANT
  - KELP
  - VINE
ignored-blocks:
  - WEEPING_VINES
  - TWISTING_VINES
  - CRIMSON_ROOTS
  - NETHER_SPROUTS
  - WARPED_FUNGUS
  - CRIMSON_FUNGUS
  - GRASS
  - SNOW
  - FERN
settings:
  default:
    world-NORMAL:
      max-y: 85
      offsets:
        x: 0
        y: 1
        z: 0
    world-THE_END:
      max-y: 255
      offsets:
        x: 0
        y: 1
        z: 0
      start-y: 50
    world-NETHER:
      max-y: 255
      check-lava: 25
      start-y: 60
      end-y: 25
      offsets:
        x: 0
        y: 0
        z: 0
    check-for-evenness:
      poz:
        start-y: 0
        end-y: 2
        start-x: -2
        end-x: 3
        start-z: -2
        end-z: 3
  custom:
    world-NORMAL:
      max-y: 85
      offsets:
        x: 0
        y: 2
        z: 0
    world-THE_END:
      max-y: 255
      offsets:
        x: 0
        y: 1
        z: 0
      start-y: 50
    world-NETHER:
      max-y: 255
      check-lava: 25
      start-y: 60
      end-y: 25
      offsets:
        x: 0
        y: 0
        z: 0
    check-for-evenness:
      poz:
        start-y: 0
        end-y: 3
        start-x: -3
        end-x: 4
        start-z: -3
        end-z: 4